// This file was generated by a program.
package mypackage

// package names to be imported

///////////////////////////////////////////////
// functions for State CountdownStm0WaitOneSec
///////////////////////////////////////////////

func CountdownStm0WaitOneSecEntry() {
	if debug {
		logger.Println("Entering State CountdownStm0WaitOneSec")
	}
	count = 0
}

func CountdownStm0WaitOneSecDo() {
	count++
}

func CountdownStm0WaitOneSecExit() {
	if debug {
		logger.Println("Leaving State CountdownStm0WaitOneSec")
	}
	// Please write an exit process for State CountdownStm0WaitOneSec
}

///////////////////////////////////////////////
// functions for State CountdownStm0CountdownWaitRelease
///////////////////////////////////////////////

func CountdownStm0CountdownWaitReleaseEntry() {
	if debug {
		logger.Println("Entering State CountdownStm0CountdownWaitRelease")
	}
	// Please write an enter process for State CountdownStm0CountdownWaitRelease
}

func CountdownStm0CountdownWaitReleaseDo() {
	// Please write a do process for State CountdownStm0CountdownWaitRelease
}

func CountdownStm0CountdownWaitReleaseExit() {
	if debug {
		logger.Println("Leaving State CountdownStm0CountdownWaitRelease")
	}
	// Please write an exit process for State CountdownStm0CountdownWaitRelease
}

///////////////////////////////////////////////
// Conditions
///////////////////////////////////////////////

func CountdownStm0WaitOneSeconeSecPassCond() bool {
	return count == countSecond
}

func CountdownStm0WaitOneSecstopButtonPushCond() bool {
	return !rRelease
}

///////////////////////////////////////////////
// Actions
///////////////////////////////////////////////

func CountdownStm0WaitOneSeconeSecPassAction() {
	countDown()
	// displayTime()
}

func CountdownStm0WaitOneSecstopButtonPushAction() {
	// Please edit the action when stopButtonPush occurs at State WaitOneSec
}
