// This file was generated by a program.
// Please do not edit this file directly.
package mypackage

import (
// package names to be imported
)

type rootStm2State uint8

const (
	rootStm2AlarmOn rootStm2State = iota
	rootStm2Countdown
	rootStm2TimerSet
)

var rootStm2Eod Eod

var rootStm2CurrentState rootStm2State

func init() {
	rootStm2Initialize()
}

func rootStm2Initialize() {
	rootStm2CurrentState = rootStm2TimerSet
}

func EntryrootStm2Task() {
	rootStm2Task()
}

func rootStm2Task() {
	switch rootStm2CurrentState {
	case rootStm2AlarmOn:
		if rootStm2Eod == Entry {
			rootStm2AlarmOnEntry()
			rootStm2Eod = Do
		}
		if rootStm2Eod == Do {
			rootStm2AlarmOnDo()
			if rootStm2AlarmOnstopButtonReleaseCond() {
				rootStm2AlarmOnstopButtonReleaseAction()
				rootStm2CurrentState = rootStm2TimerSet
				rootStm2Eod = Exit
			}
		}
		if rootStm2Eod == Exit {
			rootStm2AlarmOnExit()
			rootStm2Eod = Entry
		}
	case rootStm2Countdown:
		if rootStm2Eod == Entry {
			rootStm2CountdownEntry()
			rootStm2Eod = Do
		}
		if rootStm2Eod == Do {
			rootStm2CountdownDo()
			if rootStm2CountdowncountDownEndCond() {
				rootStm2CountdowncountDownEndAction()
				rootStm2CurrentState = rootStm2AlarmOn
				rootStm2Eod = Exit
			}
			if rootStm2CountdownstopButtonReleaseCond() {
				rootStm2CountdownstopButtonReleaseAction()
				rootStm2CurrentState = rootStm2TimerSet
				rootStm2Eod = Exit
			}
		}
		if rootStm2Eod == Exit {
			rootStm2CountdownExit()
			rootStm2Eod = Entry
		}
	case rootStm2TimerSet:
		if rootStm2Eod == Entry {
			rootStm2TimerSetEntry()
			rootStm2Eod = Do
		}
		if rootStm2Eod == Do {
			rootStm2TimerSetDo()
			if rootStm2TimerSetstartButtonReleaseCond() {
				rootStm2TimerSetstartButtonReleaseAction()
				rootStm2CurrentState = rootStm2Countdown
				rootStm2Eod = Exit
			}
		}
		if rootStm2Eod == Exit {
			rootStm2TimerSetExit()
			rootStm2Eod = Entry
		}
	}
}
