// This file was generated by a program.
package mypackage

// package names to be imported

///////////////////////////////////////////////
// functions for State CountdownStm1WaitOneSec
///////////////////////////////////////////////

func CountdownStm1WaitOneSecEntry() {
	if debug {
		logger.Println("Entering State CountdownStm1WaitOneSec")
	}
	count = 0
}

func CountdownStm1WaitOneSecDo() {
	count++
}

func CountdownStm1WaitOneSecExit() {
	if debug {
		logger.Println("Leaving State CountdownStm1WaitOneSec")
	}
	// Please write an exit process for State CountdownStm1WaitOneSec
}

///////////////////////////////////////////////
// functions for State CountdownStm1CountdownWaitRelease
///////////////////////////////////////////////

func CountdownStm1CountdownWaitReleaseEntry() {
	if debug {
		logger.Println("Entering State CountdownStm1CountdownWaitRelease")
	}
	// Please write an enter process for State CountdownStm1CountdownWaitRelease
}

func CountdownStm1CountdownWaitReleaseDo() {
	// Please write a do process for State CountdownStm1CountdownWaitRelease
}

func CountdownStm1CountdownWaitReleaseExit() {
	if debug {
		logger.Println("Leaving State CountdownStm1CountdownWaitRelease")
	}
	// Please write an exit process for State CountdownStm1CountdownWaitRelease
}

///////////////////////////////////////////////
// Conditions
///////////////////////////////////////////////

func CountdownStm1WaitOneSeconeSecPassCond() bool {
	return count == countSecond
}

func CountdownStm1WaitOneSecstopButtonPushCond() bool {
	return !rRelease
}

///////////////////////////////////////////////
// Actions
///////////////////////////////////////////////

func CountdownStm1WaitOneSeconeSecPassAction() {
	countDown()
	// displayTime()
}

func CountdownStm1WaitOneSecstopButtonPushAction() {
	// Please edit the action when stopButtonPush occurs at State WaitOneSec
}
