// This file was generated by a program.
package mypackage

// package names to be imported

///////////////////////////////////////////////
// functions for State TimerSetStm2Idle
///////////////////////////////////////////////

func TimerSetStm2IdleEntry() {
	if debug {
		logger.Println("Entering State TimerSetStm2Idle")
	}
	// displayTimer()
}

func TimerSetStm2IdleDo() {
	// Please write a do process for State TimerSetStm2Idle
}

func TimerSetStm2IdleExit() {
	if debug {
		logger.Println("Leaving State TimerSetStm2Idle")
	}
	// Please write an exit process for State TimerSetStm2Idle
}

///////////////////////////////////////////////
// functions for State TimerSetStm2AddOneMin
///////////////////////////////////////////////

func TimerSetStm2AddOneMinEntry() {
	if debug {
		logger.Println("Entering State TimerSetStm2AddOneMin")
	}
	addMinute()
	// displayTimer()
}

func TimerSetStm2AddOneMinDo() {
	// Please write a do process for State TimerSetStm2AddOneMin
}

func TimerSetStm2AddOneMinExit() {
	if debug {
		logger.Println("Leaving State TimerSetStm2AddOneMin")
	}
	// Please write an exit process for State TimerSetStm2AddOneMin
}

///////////////////////////////////////////////
// functions for State TimerSetStm2AddOneSec
///////////////////////////////////////////////

func TimerSetStm2AddOneSecEntry() {
	if debug {
		logger.Println("Entering State TimerSetStm2AddOneSec")
	}
	addSecond()
	// displayTimer()
}

func TimerSetStm2AddOneSecDo() {
	// Please write a do process for State TimerSetStm2AddOneSec
}

func TimerSetStm2AddOneSecExit() {
	if debug {
		logger.Println("Leaving State TimerSetStm2AddOneSec")
	}
	// Please write an exit process for State TimerSetStm2AddOneSec
}

///////////////////////////////////////////////
// functions for State TimerSetStm2TimerWaitRelease
///////////////////////////////////////////////

func TimerSetStm2TimerWaitReleaseEntry() {
	if debug {
		logger.Println("Entering State TimerSetStm2TimerWaitRelease")
	}
	// displayTimer()
}

func TimerSetStm2TimerWaitReleaseDo() {
	// Please write a do process for State TimerSetStm2TimerWaitRelease
}

func TimerSetStm2TimerWaitReleaseExit() {
	if debug {
		logger.Println("Leaving State TimerSetStm2TimerWaitRelease")
	}
	// Please write an exit process for State TimerSetStm2TimerWaitRelease
}

///////////////////////////////////////////////
// functions for State TimerSetStm2Set
///////////////////////////////////////////////

func TimerSetStm2SetEntry() {
	if debug {
		logger.Println("Entering State TimerSetStm2Set")
	}
	// displayTimer()
}

func TimerSetStm2SetDo() {
	// Please write a do process for State TimerSetStm2Set
}

func TimerSetStm2SetExit() {
	if debug {
		logger.Println("Leaving State TimerSetStm2Set")
	}
	// Please write an exit process for State TimerSetStm2Set
}

///////////////////////////////////////////////
// Conditions
///////////////////////////////////////////////

func TimerSetStm2IdleSecButtonPushCond() bool {
	return !mRelease
}

func TimerSetStm2IdleMinButtonPushCond() bool {
	return !lRelease
}

func TimerSetStm2AddOneMinMinButtonReleaseCond() bool {
	return lRelease
}

func TimerSetStm2AddOneSecSecButtonReleaseCond() bool {
	return mRelease
}

func TimerSetStm2SetstartButtonPushCond() bool {
	return !rRelease
}

func TimerSetStm2SetSecButtonPushCond() bool {
	return !mRelease
}

func TimerSetStm2SetMinButtonPushCond() bool {
	return !lRelease
}

///////////////////////////////////////////////
// Actions
///////////////////////////////////////////////

func TimerSetStm2IdleSecButtonPushAction() {
	// Please edit the action when SecButtonPush occurs at State Idle
}

func TimerSetStm2IdleMinButtonPushAction() {
	// Please edit the action when MinButtonPush occurs at State Idle
}

func TimerSetStm2AddOneMinMinButtonReleaseAction() {
	// Please edit the action when MinButtonRelease occurs at State AddOneMin
}

func TimerSetStm2AddOneSecSecButtonReleaseAction() {
	// Please edit the action when SecButtonRelease occurs at State AddOneSec
}

func TimerSetStm2SetstartButtonPushAction() {
	// Please edit the action when startButtonPush occurs at State Set
}

func TimerSetStm2SetSecButtonReleaseAction() {
	// Please edit the action when SecButtonRelease occurs at State Set
}

func TimerSetStm2SetMinButtonPushAction() {
	// Please edit the action when MinButtonPush occurs at State Set
}
