// This file was generated by a program.
// Please do not edit this file directly.
package mypackage

// package names to be imported

type TimerSetStm2State uint8

const (
	TimerSetStm2Idle TimerSetStm2State = iota
	TimerSetStm2AddOneMin
	TimerSetStm2AddOneSec
	TimerSetStm2TimerWaitRelease
	TimerSetStm2Set
)

var TimerSetStm2Eod Eod

var TimerSetStm2CurrentState TimerSetStm2State

func init() {
	TimerSetStm2Initialize()
}

func TimerSetStm2Initialize() {
	TimerSetStm2CurrentState = TimerSetStm2Idle
}

func TimerSetStm2Task() {
	switch TimerSetStm2CurrentState {
	case TimerSetStm2Idle:
		if TimerSetStm2Eod == Entry {
			TimerSetStm2IdleEntry()
			TimerSetStm2Eod = Do
		}
		if TimerSetStm2Eod == Do {
			TimerSetStm2IdleDo()
			if TimerSetStm2IdleSecButtonPushCond() {
				TimerSetStm2IdleSecButtonPushAction()
				TimerSetStm2CurrentState = TimerSetStm2AddOneSec
				TimerSetStm2Eod = Exit
			}
			if TimerSetStm2IdleMinButtonPushCond() {
				TimerSetStm2IdleMinButtonPushAction()
				TimerSetStm2CurrentState = TimerSetStm2AddOneMin
				TimerSetStm2Eod = Exit
			}
		}
		if TimerSetStm2Eod == Exit {
			TimerSetStm2IdleExit()
			TimerSetStm2Eod = Entry
		}
	case TimerSetStm2AddOneMin:
		if TimerSetStm2Eod == Entry {
			TimerSetStm2AddOneMinEntry()
			TimerSetStm2Eod = Do
		}
		if TimerSetStm2Eod == Do {
			TimerSetStm2AddOneMinDo()
			if TimerSetStm2AddOneMinMinButtonReleaseCond() {
				TimerSetStm2AddOneMinMinButtonReleaseAction()
				TimerSetStm2CurrentState = TimerSetStm2Set
				TimerSetStm2Eod = Exit
			}
		}
		if TimerSetStm2Eod == Exit {
			TimerSetStm2AddOneMinExit()
			TimerSetStm2Eod = Entry
		}
	case TimerSetStm2AddOneSec:
		if TimerSetStm2Eod == Entry {
			TimerSetStm2AddOneSecEntry()
			TimerSetStm2Eod = Do
		}
		if TimerSetStm2Eod == Do {
			TimerSetStm2AddOneSecDo()
			if TimerSetStm2AddOneSecSecButtonReleaseCond() {
				TimerSetStm2AddOneSecSecButtonReleaseAction()
				TimerSetStm2CurrentState = TimerSetStm2Set
				TimerSetStm2Eod = Exit
			}
		}
		if TimerSetStm2Eod == Exit {
			TimerSetStm2AddOneSecExit()
			TimerSetStm2Eod = Entry
		}
	case TimerSetStm2TimerWaitRelease:
		if TimerSetStm2Eod == Entry {
			TimerSetStm2TimerWaitReleaseEntry()
			TimerSetStm2Eod = Do
		}
		if TimerSetStm2Eod == Do {
			TimerSetStm2TimerWaitReleaseDo()
		}
		if TimerSetStm2Eod == Exit {
			TimerSetStm2TimerWaitReleaseExit()
			TimerSetStm2Eod = Entry
		}
	case TimerSetStm2Set:
		if TimerSetStm2Eod == Entry {
			TimerSetStm2SetEntry()
			TimerSetStm2Eod = Do
		}
		if TimerSetStm2Eod == Do {
			TimerSetStm2SetDo()
			if TimerSetStm2SetstartButtonPushCond() {
				TimerSetStm2SetstartButtonPushAction()
				TimerSetStm2CurrentState = TimerSetStm2TimerWaitRelease
				TimerSetStm2Eod = Exit
			}
			if TimerSetStm2SetSecButtonPushCond() {
				TimerSetStm2SetSecButtonReleaseAction()
				TimerSetStm2CurrentState = TimerSetStm2AddOneSec
				TimerSetStm2Eod = Exit
			}
			if TimerSetStm2SetMinButtonPushCond() {
				TimerSetStm2SetMinButtonPushAction()
				TimerSetStm2CurrentState = TimerSetStm2AddOneMin
				TimerSetStm2Eod = Exit
			}
		}
		if TimerSetStm2Eod == Exit {
			TimerSetStm2SetExit()
			TimerSetStm2Eod = Entry
		}
	}
}
