// This file was generated by a program.
package mypackage

// package names to be imported

type Eod uint8

const (
	Entry Eod = iota
	Do
	Exit
)

type DebugLogger interface {
	Println(string)
}

var logger DebugLogger

func ConfigureLog(p DebugLogger) {
	logger = p
}

const (
	debug = true
)

const (
	countSecond = 18
)

type Switch interface {
	Get() bool
}

var buttonL Switch
var buttonM Switch
var buttonR Switch

func ConfigureLeftButton(s Switch) {
	buttonL = s
}

func ConfigureMiddleButton(s Switch) {
	buttonM = s
}

func ConfigureRightButton(s Switch) {
	buttonR = s
}

// interface Monitor
// ディスプレイに文字が表示され、表示が更新されることを確認するためのインターフェース
type Monitor interface {
	PrintVal(string)
}

var display Monitor

func ConfigureMonitor(m Monitor) {
	display = m
}

// interface Alarm
// アラームがなることを確認するためのインターフェース
type Alarm interface {
	Beep()
	Mute()
}

var alarm Alarm

func ConfigureAlarm(a Alarm) {
	alarm = a
}

var mm int = 0
var ss int = 0

var inputEnabledL bool = true
var inputEnabledM bool = true
var inputEnabledR bool = true

var count int = 0
