// This file was generated by a program.
// Please do not edit this file directly.
package mypackage

// package names to be imported

type CountdownStm1State uint8

const (
	CountdownStm1WaitOneSec CountdownStm1State = iota
	CountdownStm1OneSecDecrease
	CountdownStm1CountdownWaitRelease
)

var CountdownStm1Eod Eod

var CountdownStm1CurrentState CountdownStm1State

func init() {
	CountdownStm1Initialize()
}

func CountdownStm1Initialize() {
	CountdownStm1CurrentState = CountdownStm1WaitOneSec
}

func CountdownStm1Task() {
	switch CountdownStm1CurrentState {
	case CountdownStm1WaitOneSec:
		if CountdownStm1Eod == Entry {
			CountdownStm1WaitOneSecEntry()
			CountdownStm1Eod = Do
		}
		if CountdownStm1Eod == Do {
			CountdownStm1WaitOneSecDo()
			if CountdownStm1WaitOneSeconeSecPassCond() {
				CountdownStm1WaitOneSeconeSecPassAction()
				CountdownStm1CurrentState = CountdownStm1OneSecDecrease
				CountdownStm1Eod = Exit
			}
			if CountdownStm1WaitOneSecstopButtonPushCond() {
				CountdownStm1WaitOneSecstopButtonPushAction()
				CountdownStm1CurrentState = CountdownStm1CountdownWaitRelease
				CountdownStm1Eod = Exit
			}
		}
		if CountdownStm1Eod == Exit {
			CountdownStm1WaitOneSecExit()
			CountdownStm1Eod = Entry
		}
	case CountdownStm1OneSecDecrease:
		if CountdownStm1Eod == Entry {
			CountdownStm1OneSecDecreaseEntry()
			CountdownStm1Eod = Do
		}
		if CountdownStm1Eod == Do {
			CountdownStm1OneSecDecreaseDo()
			if CountdownStm1OneSecDecreasenothingCond() {
				CountdownStm1OneSecDecreasenothingAction()
				CountdownStm1CurrentState = CountdownStm1WaitOneSec
				CountdownStm1Eod = Exit
			}
		}
		if CountdownStm1Eod == Exit {
			CountdownStm1OneSecDecreaseExit()
			CountdownStm1Eod = Entry
		}
	case CountdownStm1CountdownWaitRelease:
		if CountdownStm1Eod == Entry {
			CountdownStm1CountdownWaitReleaseEntry()
			CountdownStm1Eod = Do
		}
		if CountdownStm1Eod == Do {
			CountdownStm1CountdownWaitReleaseDo()
		}
		if CountdownStm1Eod == Exit {
			CountdownStm1CountdownWaitReleaseExit()
			CountdownStm1Eod = Entry
		}
	}
}
