// This file was generated by a program.
package mypackage

import "fmt"

// package names to be imported

///////////////////////////////////////////////
// functions for State CountdownStm1WaitOneSec
///////////////////////////////////////////////

func CountdownStm1WaitOneSecEntry() {
	if debug {
		// logger.Println("Entering State CountdownStm1WaitOneSec")
	}
	// Please write an enter process for State CountdownStm1WaitOneSec
}

func CountdownStm1WaitOneSecDo() {
	count++
}

func CountdownStm1WaitOneSecExit() {
	if debug {
		// logger.Println("Leaving State CountdownStm1WaitOneSec")
	}
	// Please write an exit process for State CountdownStm1WaitOneSec
}

///////////////////////////////////////////////
// functions for State CountdownStm1OneSecDecrease
///////////////////////////////////////////////

func displayTime() {
	if ss%2 == 1 {
		display.PrintVal(fmt.Sprintf("%02d : %02d", mm, ss))
	} else {
		display.PrintVal(fmt.Sprintf("%02d   %02d", mm, ss))
	}
}

func countDown() {
	ss--
	if ss == -1 {
		if mm == 0 {
			ss = 0
		} else {
			ss = 59
			mm--
		}
	}
}

func CountdownStm1OneSecDecreaseEntry() {
	if debug {
		// logger.Println("Entering State CountdownStm1OneSecDecrease")
	}

	countDown()
	displayTime()
}

func CountdownStm1OneSecDecreaseDo() {
	// Please write a do process for State CountdownStm1OneSecDecrease
}

func CountdownStm1OneSecDecreaseExit() {
	if debug {
		// logger.Println("Leaving State CountdownStm1OneSecDecrease")
	}
	count = 0
}

///////////////////////////////////////////////
// functions for State CountdownStm1CountdownWaitRelease
///////////////////////////////////////////////

func CountdownStm1CountdownWaitReleaseEntry() {
	if debug {
		logger.Println("Entering State CountdownStm1CountdownWaitRelease")
	}
	// Please write an enter process for State CountdownStm1CountdownWaitRelease
}

func CountdownStm1CountdownWaitReleaseDo() {
	// Please write a do process for State CountdownStm1CountdownWaitRelease
}

func CountdownStm1CountdownWaitReleaseExit() {
	if debug {
		logger.Println("Leaving State CountdownStm1CountdownWaitRelease")
	}
	// Please write an exit process for State CountdownStm1CountdownWaitRelease
}

///////////////////////////////////////////////
// Conditions
///////////////////////////////////////////////

func CountdownStm1WaitOneSeconeSecPassCond() bool {
	return count == countSecond
}

func CountdownStm1WaitOneSecstopButtonPushCond() bool {
	return !buttonR.Get()
}

func CountdownStm1OneSecDecreasenothingCond() bool {
	return true
}

///////////////////////////////////////////////
// Actions
///////////////////////////////////////////////

func CountdownStm1WaitOneSeconeSecPassAction() {
	// Please edit the action when oneSecPass occurs at State WaitOneSec
}

func CountdownStm1WaitOneSecstopButtonPushAction() {
	// Please edit the action when stopButtonPush occurs at State WaitOneSec
}

func CountdownStm1OneSecDecreasenothingAction() {
	// Please edit the action when nothing occurs at State OneSecDecrease
}
